language: scala

scala:
  - 2.12.8

jdk: oraclejdk8

env:
  global:
    - secure: "CfKKI1Es1abl2cpPitEaFfX/lWAqQOBfR+XhELoCyfP00Mixkp8XevvuC+cqVT389LQsBsx4y/IjAO1elGSRX6vDEN5SpYe2+WG+Ocbz9BHH/lX+Ulh0lMci45c0nK6pxMNZyEu7+wdi5tBpj++f6RCHNCq1TZJ+vQ3W6BwuA3nGVpp4VnOJqpG9jXaEOT1y7cmJ/B5yY9pZ1ZhrtfYUXdnm1ijS6/eclMeGxkvL5i5I5t8Ot6hYEezOEjIloJ0PF+4uW5EwP0R0Mne0gpz5G96Wn+eTovDdbh5t8LpRsE0MvI24GXeo0P2OJS6OGvd48ofClQFVxOSpivT6bd6zEhmhH5JJMUBiC+76ak9N+xFdivPGX2S4BjkHQaZFsrRMJI57uGZtFSzi6Jd0jH+mTFkAW8Z49qeAGbeS5iqEZRHxtBNH/YJBoIol3sl3fA06bHmBgWA9f/EdPuu6MQ6IObziGK54fvWg3434Wi8V7FQmDtwCVdlmEewS9Sp6J7Z2tdrM7P6pkwdb2fD45wjs9bp2PXKs4ulOQlUGTd375CG44rKKY4nnHLwYWlaeNfSgp4owLMbKlswQFQHGWhaeNFXTIMzzQsQjGdWmju1tN2AgY2dQ2c0UEt5IgAHjIGneaEeoaE/+UF3g7TJKM1/s3D7xLf7AcC9D7Ay/zmFiAKg="

before_script:
  - jdk_switcher use $JDK

script: sbt ++$TRAVIS_SCALA_VERSION test

before_deploy:
  - mkdir -p $HOME/.bintray
  - openssl aes-256-cbc -K $encrypted_9d26de061da6_key -iv $encrypted_9d26de061da6_iv -in .credentials.enc -out $HOME/.bintray/.credentials -d

deploy:
  - provider: script
    script: .travis/release.sh
    on:
      branch: 4.x
      scala: 2.12.8
      condition: $(git log -n1 --format=format:"%an") != "Dwolla Bot"
